## swiftlint.yml
## https://github.com/realm/SwiftLint

## Install
## or #1
## brew install swiftlint

## Run Script Phase
# if which swiftlint >/dev/null; then
#   swiftlint
# else
#   echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
# fi

## or #2
## pod 'SwiftLint'

## Run Script Phase
# "${PODS_ROOT}/SwiftLint/swiftlint"



#included:
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- Carthage
- R.generated.swift
#- Source/ExcludedFolder
#- Source/ExcludedFile.swift

disabled_rules:
- trailing_whitespace
- force_try
- force_cast
- notification_center_detachment
#- function_parameter_count

opt_in_rules:
  - attributes
  - closure_spacing
  - overridden_super_call
  - object_literal ## not UIImage(named: "qwe"), use #imageLiteral(resourceName: "im_cloud")
  - switch_case_on_newline
  - vertical_parameter_alignment_on_call
  - implicit_return ## not return for single line
  - fatal_error_message
  - empty_count ## not count > 0, use isEmpty(extension notEmpty)

  # - conditional_returns_on_newline ## not { return }, use {\n return \n}
  # - explicit_top_level_acl ## use public for 
  # - explicit_type_interface ## not = "", use : String = ""
  # - extension_access_modifier ## use public for extensions
  # - sorted_imports
  # - operator_usage_whitespace ## not 2+2, use 2 + 2
  # - number_separator #1_000
  # - private_outlet
  # - implicitly_unwrapped_optional ## not ! for properties
  # - force_unwrapping
  # - first_where ## ???
  # - multiline_parameters ## ???
  # - nimble_operator ## ???
  # - closure_end_indentation ## ???
  # - closure_spacing ## ???
  # - explicit_init ## ???

## ---------- rules settings ----------

line_length:
- 180 #warning
- 480 #error

vertical_whitespace:
  max_empty_lines: 2

cyclomatic_complexity:
  ignores_case_statements: true
  #warning: 10
  #error: 20

function_body_length:
  warning: 50
  error: 100

identifier_name:
  validates_start_with_lowercase: true
  min_length:
    warning: 2
    error: 1
  # max_length:
  #   warning: 40
  #   error: 60
  # excluded:
  #   - id
  #   - URL
  # allowed_symbols: []

# file_length:
#   warning: 500
#   error: 1200

## opt_in
attributes:
  severity: warning
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
  #always_on_line_above: []

## opt_in
# private_outlet:
#   allow_private_set: true